services:
  influxdb_twin:
    image: influxdb:2.7
    container_name: influxdb_twin
    restart: unless-stopped
    ports:
      - "8087:8086"
    volumes:
      - influxdb_twin_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=12345678
      - DOCKER_INFLUXDB_INIT_ORG=IASBS
      - DOCKER_INFLUXDB_INIT_BUCKET=solar_twin
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=wxL_ZDwcyLN2v13A1ncNyrJwYSFcSgAdhZLekHELkUWnnUL3_b8Ej04pr-b2e4NdTiRu1m4eyrqI86WC6uxxBA==

  grafana_twin:
    image: grafana/grafana:latest
    container_name: grafana_twin
    restart: unless-stopped
    ports:
      - "3001:3000"
    depends_on:
      - influxdb_twin
    volumes:
      - grafana_twin_data:/var/lib/grafana

volumes:
  influxdb_twin_data:
  grafana_twin_data:
